# Generated by Django 5.2.1 on 2025-06-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_videostudio_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloartist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soloartist',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='soloartist',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
