# Generated by Django 5.2 on 2025-07-29 10:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_alter_choir_cover_image_alter_choir_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='song_end_time',
            field=models.FloatField(blank=True, help_text='End time for audio clip (in seconds)', null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='song_start_time',
            field=models.FloatField(blank=True, help_text='Start time for audio clip (in seconds)', null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/YOUR_CLOUD_NAME/image/upload/v1234567890/profiles/default.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.track'),
        ),
    ]
